image: docker:20.10.16

pipelines:
  default:
    - step:
        name: Build and Push Keycloak Image
        services:
          - docker
        caches:
          - docker
        script:
          - echo "$HARBOR_PASSWORD" | docker login -u "$HARBOR_USERNAME" --password-stdin "$HARBOR_REGISTRY"
          - docker build -t "$HARBOR_REGISTRY/$HARBOR_PROJECT/keycloak:latest" .
          - docker push "$HARBOR_REGISTRY/$HARBOR_PROJECT/keycloak:latest"
